version: '3.9'
services:
    vault-api:
        build: .
        container_name: vault-api
        image: vault-api:dev
        ports:
            - '8080:8080'
        volumes:
            - .:/app
            - ./db:/app/db
            - /app/node_modules
        env_file:
            - .env
